require 'naskit'
require 'webmock/rspec'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.before do
    stub_request(:get, "http://naskit.thirdside.ca/search/?q=How.I.Met.Your.Mother.S01E01.mpeg").with(
      :headers => { 'Accept' => 'application/json' }
    ).to_return(
      :body => "",
      :status => 301,
      :headers => {
        'Location' => "http://naskit.thirdside.ca/shows/1/seasons/1/episodes/1"
      }
    )

    stub_request(:get, "http://naskit.thirdside.ca/shows/1/seasons/1/episodes/1").with(
      :headers => {'Accept' => 'application/json'}
    ).to_return(
      :body => '{"title":"Pilot","number":1,"description":"Episode Description\n","season":1,"show":"How I Met Your Mother"}',
      :headers => {
        'Content-Length' => 109,
        'Content-Type' => 'application/json'
      }
    )
  end
end
